checks:
  php:
    code_rating: true
    duplication: true

before_commands:
  - "composer install --no-interaction"

filter:
  excluded_paths:
    - tests/*

build:
  environment:
    php: "7.4"
  nodes:
    coverage:
      tests:
        override:
          - command: "vendor/bin/phpunit --colors=always --coverage-clover coverage.clover tests"
            coverage:
              file: coverage.clover
              format: clover